name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 103.37.125.218
        username: lixie
        password: Eky12345
        port: 22
        script: |
          pwd
          sudo su; git pull /var/www/html/tes-cicd
